### PR TITLE
#57 - Fix effects for config and auth

### LINKED ISSUE #57: Investigate and fix use of `useAxios`
The central idea is that there should be a single axios instance and any code that needs to fetch data will use that instance. We believe this to be necessary because whenever authorization is enabled, request headers need to be updated and it makes the most sense for that to happen in exactly one place.

#### BACKGROUND
- `src/hooks/useMyAxios.ts` provides a `getUseAxios`. This can be ignored. It's a pattern that was adopted to make legacy code work with authorization with the least amount of effort. It is not used in any newer code.
- `src/hooks/useMyAxios.ts`  also provides an `axiosInstance`
   - This serves as the axios instance singleton
   - In some code, this is exactly what we need. For example, in  `src/hooks/useToken.ts::useToken()` we need to directly manipulate the axios instance in order to update the interceptor that then updates the request headers.
   - In most code that makes use of axios, we adopt a different pattern. For example, in `src/pages/SystemIndex/SystemIndexTable/data.tsx`, [we make use of the `useAxios` hook](https://github.com/beer-garden/react-ui/blob/0380c1d9a26f0521f0b376ac232aefe00cc1a40d/src/pages/SystemIndex/SystemIndexTable/data.tsx#L33) (from `axios-hooks`) . This allows us to only monitor the `data` and `error`  returned from the hook via a `useEffect`, thus making the code shorter and more easily understood (versus something like `axios.get().then(() => {success code}).catch(() => {error code})` or its `async` equivalent being duplicated all over the place).
   - The call to `configure` (from `axios-hooks`) in `useToken` evidently ensures that any later calls to `useAxios` does in fact utilize the axios instance from `useMyAxios`

#### PROBLEMS
- [It appears that the use of a function variable](https://github.com/beer-garden/react-ui/blob/0380c1d9a26f0521f0b376ac232aefe00cc1a40d/src/components/Routes/Routes.tsx#L28) (whose dependencies eventually resolve back to a dependency on the axios singleton) will result in an infinite loop whenever that function variable is in the dependency array of, for example, a `useEffect`
- Some uses of `useAxios` as described above are causing double fetches after an error response. Others are not causing this behavior at all.

#### REQUIREMENT FOR THIS ISSUE
The nested hierarchies of `useState`, `useMemo`, `useCallback`, etc. can make determining the exact cause of a bug extremely difficult (one of the major negatives of using react, if you believe the blogs). Consequently, the root cause of problem 1 could be something entirely different. Hence, a solution should
- Verify if the actual root cause of problem 1 is actually as explained or is something else entirely
- Fix the actual root cause of problem 1
- Determine whether continued use of the `useAxios` pattern explained above should be retained. Whether it should or should not be retained, refactor existing code into a form that will eliminate the double fetches + *Cancel* error

### PR DESCRIPTION
**Pull request by kvig**
Closes #57 
- Switch `authEnabled` and `debugEnabled` in `ServerConfigContainer` to be memoized variables vs functions
- Add missing `getConfig` dependency to the config retrieval in Routes
- Fix the double fetch of the `Request` table's data - Add more useCallbacks and useMemo's for data that shouldn't be changing or doesn't need to be recomputed.
- Update `useToken::setToken()` to save the Request and Response handlers as callbacks, also remove the old interceptors when adding new ones

With appropriate useCallback and useMemo's, the current `axiosInstance`/`useAxios` pattern is sufficient.

### CODE REVIEW

File: src/hooks/useMyAxios.ts [hunk 1]
```diff
@@ -1,17 +1,13 @@
...
-const BASE_URL = 'http://localhost:2337/' // TODO
-const BASIC_REQUEST_CONFIG: AxiosRequestConfig = {
-  baseURL: BASE_URL,
-}
+import { useCallback, useMemo } from 'react'
 
 const useMyAxios = () => {
   // const axiosInstance: AxiosInstance = Axios.create(BASIC_REQUEST_CONFIG)
-  const axiosInstance: AxiosInstance = Axios.create()
+  const axiosInstance: AxiosInstance = useMemo(() => { return Axios.create() }, [])
```
Comment (jlrpnbbngtn) [inline src/hooks/useMyAxios.ts:7]: Does `useMemo` with an empty array do anything that its omission would not?

File: src/hooks/useToken.ts [hunk 2]
```diff
@@ -63,40 +63,45 @@ export const useToken = (
     clearAutomaticTokenRefresh()
   }, [setRefreshToken, clearAutomaticTokenRefresh])
 
+  const requestInterceptor = useCallback((config: AxiosRequestConfig): AxiosRequestConfig => {
```
Comment (jlrpnbbngtn) [inline src/hooks/useToken.ts:66]: This is a great refactor. Everything's much clearer now.

**Review by jlrpnbbngtn — APPROVED** [review]
Two minor comments, one question for my own knowledge. No blocks, clear to merge.

File: src/hooks/useMyAxios.ts [hunk 3]
```diff
@@ -1,17 +1,13 @@
-import Axios, { AxiosInstance, AxiosRequestConfig } from 'axios'
+import Axios, { AxiosInstance } from 'axios'
 import { makeUseAxios } from 'axios-hooks'
-import { useCallback } from 'react'
-
-const BASE_URL = 'http://localhost:2337/' // TODO
```
[the remark this answers is not in the document]
Comment (kvig) [reply src/hooks/useMyAxios.ts:5]: The config for the server can be stored in `src/config/config.js` and imported via js syntax. Another library I previously used is `dotenv`. We used it to import some configuration we didn't want to version control, this was in the traditional `key=value` format.

File: src/hooks/useMyAxios.ts (hunk 1 above)
Comment (kvig) [reply src/hooks/useMyAxios.ts:7]: Omitting the [] would cause the `Axios.create()` call to execute on every render, which then causes `useEffect`s to re-fire. 

Each use of the `axiosInstance` from this creates a new usable object with the correct URL to make the fetch call. I did verify that the token gets updated on the request when the timeout occurs after 15 minutes and doesn't force any unnecessary refreshes.

Comment (jlrpnbbngtn) [reply src/hooks/useMyAxios.ts:7]: Sorry, I meant omitting `useMemo`, not omitting the array.

File: src/hooks/useMyAxios.ts (hunk 3 above)
[the remark this answers is not in the document]
Comment (jlrpnbbngtn) [reply src/hooks/useMyAxios.ts:5]: I looked into `dotenv` when I first considered this problem, but did not follow up. I've added it to the epic ticket.

File: src/hooks/useMyAxios.ts (hunk 1 above)
Comment (jlrpnbbngtn) [reply src/hooks/useMyAxios.ts:7]: Interesting. I think I need to work on my mental model of how exactly `useMemo` works.
